### ISSUE TITLE
I update emscripten from 1.35.0 to 1.37.0 and get compile error "unknown type name '__declspec'"

### ISSUE THREAD

**Issue by xiyanggudao** [kripken/emscripten-fastcomp-clang#15]
After I build the source of emscripten 1.37.0, I find that emcc do not recognise __declspec. In 1.35.0, It is just a warning, but now it is an error and treat __declspec as a class. The example code and error message is :
class __declspec(dllexport) A
{
};
error : unknown type name '__declspec'

Is it because the new version emscripten do not support this or I need to modify some kinds of configure ?

**Comment by kripken** [comment]
This is probably a change in upstream clang, that they decided to upgrade it from a warning to an error. I would look in the clang docs, perhaps there is a flag to modify that behavior.
