### ISSUE TITLE
`emsdk install sdk-tag-1.36.8-64bit` on Windows won't succeed

### ISSUE THREAD

**Issue by SaschaNaz** [kripken/emscripten-fastcomp-clang#9]
```
Installing SDK 'sdk-tag-1.36.8-64bit'..
Installing tool 'clang-tag-e1.36.8-64bit'..
Downloading: C:/Program Files/Emscripten/zips/llvm-e1.36.8.zip from https://github.com/kripken/emscripten-fastcomp/archi
ve/1.36.8.zip
Unpacking 'C:/Program Files/Emscripten/zips/llvm-e1.36.8.zip' to 'C:/Program Files/Emscripten/clang/tag-e1.36.8\src'
HTTP error with URL 'https://github.com/kripken/emscripten-fastcomp-clang/archive/1.36.8.zip': HTTP Error 404: Not Found
Installation failed!
```

There is no 1.36.8 release here so it fails. Can this be fixed? I want to try downgrading from 1.36.9 to 1.36.8 to see https://github.com/kripken/emscripten/issues/4506 gets fixed or not.

**Comment by kripken** [comment]
@juj, I think that would be a tag from one of your PRs - maybe it wasn't merged yet it it was merged but a tag wasn't added?

**Comment by juj** [comment]
Sorry about that, only the tag for `emscripten-fastcomp` came through, probably missed to push the `emscripten-fastcomp-clang` tag. Fixed now!
